### PR TITLE
feat: update to symplify/easy-coding-standard 12

### PR DESCRIPTION
**Pull request by rugbymauri**

### CODE REVIEW

**Comment by marcwieland95** [comment]
@rugbymauri Why is this v2.0? It's not breaking at all. It makes more sense to bump it to v1.3.0.

**Comment by xarem** [comment]
@rugbymauri @marcwieland95 if we create a v2.0 we should probably adopt https://www.php-fig.org/per/coding-style/

**Comment by marcwieland95** [comment]
> @rugbymauri @marcwieland95 if we create a v2.0 we should probably adopt https://www.php-fig.org/per/coding-style/

Agree. In the last major release we updated to PSR-12 since the rules changed.
With the upgrade to `easy-coding-standard` version 12 I don't expect bigger changes in the output of the checks. And no adjustments in the config needed. So a minor is enough for the time being.

Happy to work on a version with with the `PER Coding Style 2.0` for a v2 release.

**Comment by marcwieland95** [comment]
I updated the base branch to `develop`. Now it's correct and can be tagged as a minor

**Pull request merged**
